### ISSUE TITLE
Issue- running script locally - link does nothing

### ISSUE THREAD

**Issue by stephbush** [SeleniumBuilder/se-builder#248] opened 2015-02-25 15:15 UTC
I have a bunch of recorded tests that I can run all day long on my old computer. However, I just installed selenium builder on my brand new computer and when I open script to run it, the link Run script locally, does nothing. Any ideas?

**Comment by Zarkonnen** [comment] 2015-02-25 16:37
Any error messages in the console?

- David

**Comment by stephbush** [comment] 2015-02-25 17:33
the only error message is : use of getPreventDefault() is depracated. Use
defaultPrevented instead

this error is on console before I even try to run the script. Run >>
Run test locally and Run script locally, links do nothing. It is like
I have not clicked them. All other links on selenium builder nav work,
I can record etc.

**Comment by stephbush** [comment] 2015-02-26 03:38
Okay, it is officially due to newest version of Firefox. version 36.0
now neither of my computers can run selenium builder :(
also, I got notice when I was adding the selenium builder add-on on my new
computer with newest firefox that the add-on was not recommended or from
trusted software or whatever and I had to install it anyway...

So, what do I do now? revert to old firefox.

**Comment by brownman** [comment] 2015-03-01 11:09
+1

**Comment by jlestel** [comment] 2015-03-02 23:04
+1

**Comment by mfaure** [comment] 2015-03-08 20:35
same problem, Firefox 36.0 Ubuntu 14.04
(Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0)

**Comment by mfaure** [comment] 2015-03-09 09:36
Here are the logs given by the [Browser toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox)

# First "line"

```
Handler function DebuggerTransport.prototype.onOutputStreamReady threw an exception: [Exception... "Component returned failure code: 0x80470007 (NS_BASE_STREAM_WOULD_BLOCK) [nsIOutputStream.write]"  nsresult: "0x80470007 (NS_BASE_STREAM_WOULD_BLOCK)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/transport/packets.js :: JSONPacket.prototype.write :: line 197"  data: no]
Stack: JSONPacket.prototype.write@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/transport/packets.js:197:16
DebuggerTransport.prototype.onOutputStreamReady<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:267:6
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:13
EventLoop.prototype.enter@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:509:4
ThreadActor.prototype._pushThreadPause@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:705:4
ThreadActor.prototype.onAttach@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:816:6
DSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1485:14
DebuggerTransport.prototype._onJSONObjectReady/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:461:8
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:13
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:13
Line: 197, column: 0
```

# second "line"

```
ThreadSources.prototype._fetchSourceMap threw an exception: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stack: SourceMapConsumer@resource://gre/modules/devtools/SourceMap.jsm:67:19
ThreadSources.prototype._fetchSourceMap/fetching<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:5657:19
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:870:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:749:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:691:37
EventLoop.prototype.enter@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:509:5
ThreadActor.prototype._pushThreadPause@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:705:5
ThreadActor.prototype.onAttach@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:816:7
DSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1485:15
DebuggerTransport.prototype._onJSONObjectReady/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:461:9
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14
Line: 67, column: 18
```

**Comment by StephanieBrown** [comment] 2015-03-19 19:14
still unable to run locally, now on version firefox 36.0.1
there are no errors because when you click the Run Test Locally link it does nothing. Link seems like it is not actually a link. Same for Run Suite locally.

**Comment by IainColledge** [comment] 2015-03-30 11:18
This seems to be fixed in 2.3.1 but don't know when that will be released.

https://groups.google.com/forum/#!topic/se-builder/blEb4tG1HIg

**Comment by stephbush** [comment] 2015-03-30 11:35
Thank you!!

**Comment by IainColledge** [comment] 2015-03-30 11:47
I can confirm 2.3.1 fixes it, one can install 2.3.1 by following these notes on installing the development version of SEBuilder.

https://github.com/sebuilder/se-builder/wiki/Contribution-Notes

**Comment by Zarkonnen** [comment] 2015-03-31 09:39
Yeah, my apologies, there is a delay in officially releasing 2.3.1. Please do use the development version for now until this is resolved.

**Comment by asauber** [comment] 2015-03-31 17:26
+1 For me it looks like it was throwing

```
NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
```

On line

https://github.com/sebuilder/se-builder/blob/master/seleniumbuilder/chrome/content/html/js/builder/selenium2/playback.js#L146

Will try 2.3.1

**Comment by Zarkonnen** [comment] 2015-03-31 18:10
I'm afraid there's a delay with getting 2.3.1 officially published. I'm 
working on resolving it, and meanwhile you can use the development 
version. My apologies!

- David

**Comment by Zarkonnen** [comment] 2015-04-17 14:23
This should now be fixed and available!

**Closed by Zarkonnen** 2015-04-17 14:23 UTC

**Comment by Preeti1910** [comment] 2015-12-09 06:58
hi ,can any one solve this issue....On loading my index page this comes...

Timestamp: 12/9/2015 12:26:01 PM
Error: TabSources.prototype._fetchSourceMap threw an exception: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stack: SourceMapConsumer@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/sourcemap/source-map.js:1337:19
TabSources.prototype._fetchSourceMap/fetching<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/utils/TabSources.js:435:19
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1
EventLoop.prototype.enter@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:347:5
ThreadActor.prototype.unsafeSynchronize@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:1085:7
ThreadActor.prototype._addSource@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:1933:1
ThreadActor.prototype.onNewScript@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/script.js:1880:5
DynamicSourceCollector.prototype.onNewScript@chrome://firebug/content/debugger/script/sourceTool.js:407:1
Line: 1337, column: 19
Source File: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js
Line: 59

**Comment by Zarkonnen** [comment] 2016-02-29 13:10
I'm afraid none of these messages are related to Builder. Also, since this local playback implementation had to be removed for Builder 3 anyway, this issue may as well remain closed.
